# Generated by Django 2.2.5 on 2019-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.CharField(choices=[('editorschoice', 'political'), ('editorschoice', 'health'), ('editorschoice', 'design'), ('editorschoice', 'sports'), ('editorschoice', 'business')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
