# Generated by Django 2.2.5 on 2019-12-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cate',
            field=models.CharField(choices=[('editorschoice', 'editors_choice'), ('political', 'political'), ('health', 'health'), ('design', 'design'), ('sports', 'sports'), ('business', 'business')], max_length=20),
        ),
    ]
