# Generated by Django 2.2.5 on 2020-05-14 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_archive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='archive',
            new_name='archives',
        ),
    ]
