# Generated by Django 2.2.5 on 2020-05-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200523_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
