# Generated by Django 2.2.5 on 2020-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200523_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
