# Generated by Django 2.2.5 on 2020-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200526_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
