# Generated by Django 2.2.5 on 2020-05-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200526_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedbacks',
        ),
    ]
